<template>
    <div>
        <EasyDataTable :rows-per-page="10" :rows-items="[10, 25, 50, 100]" theme-color="#f48225" v-model:items-selected="itemsSelected" :headers="headers" :items="items" buttons-pagination/>
        
    </div>
    
    <br />
    items selected:<br />
    {{ itemsSelected }}
</template>
  
<script lang="ts">
import { defineComponent, ref } from "vue";
import Vue3EasyDataTable from "vue3-easy-data-table";

export default defineComponent({
    components: {
        EasyDataTable: Vue3EasyDataTable
    },
    setup() {
        const headers = [
            { text: "PLAYER", value: "player" },
            { text: "TEAM", value: "team" },
            { text: "NUMBER", value: "number" },
            { text: "POSITION", value: "position" },
            { text: "HEIGHT", value: "height" },
            { text: "WEIGHT (lbs)", value: "weight", sortable: true },
            { text: "LAST ATTENDED", value: "lastAttended" },
            { text: "COUNTRY", value: "country" },
        ];

        const items = [
            {
                player: "Stephen Curry",
                team: "GSW",
                number: 30,
                position: "G",
                height: "6-2",
                weight: 185,
                lastAttended: "Davidson",
                country: "USA",
            },
            {
                player: "Lebron James",
                team: "LAL",
                number: 6,
                position: "F",
                height: "6-9",
                weight: 250,
                lastAttended: "St. Vincent-St. Mary HS (OH)",
                country: "USA",
            },
            {
                player: "Kevin Durant",
                team: "BKN",
                number: 7,
                position: "F",
                height: "6-10",
                weight: 240,
                lastAttended: "Texas-Austin",
                country: "USA",
            },
            {
                player: "Giannis Antetokounmpo",
                team: "MIL",
                number: 34,
                position: "F",
                height: "6-11",
                weight: 242,
                lastAttended: "Filathlitikos",
                country: "Greece",
            },
            {
                player: "Stephen Curry",
                team: "GSW",
                number: 30,
                position: "G",
                height: "6-2",
                weight: 185,
                lastAttended: "Davidson",
                country: "USA",
            },
            {
                player: "Lebron James",
                team: "LAL",
                number: 6,
                position: "F",
                height: "6-9",
                weight: 250,
                lastAttended: "St. Vincent-St. Mary HS (OH)",
                country: "USA",
            },
            {
                player: "Kevin Durant",
                team: "BKN",
                number: 7,
                position: "F",
                height: "6-10",
                weight: 240,
                lastAttended: "Texas-Austin",
                country: "USA",
            },
            {
                player: "Giannis Antetokounmpo",
                team: "MIL",
                number: 34,
                position: "F",
                height: "6-11",
                weight: 242,
                lastAttended: "Filathlitikos",
                country: "Greece",
            },
            {
                player: "Stephen Curry",
                team: "GSW",
                number: 30,
                position: "G",
                height: "6-2",
                weight: 185,
                lastAttended: "Davidson",
                country: "USA",
            },
            {
                player: "Lebron James",
                team: "LAL",
                number: 6,
                position: "F",
                height: "6-9",
                weight: 250,
                lastAttended: "St. Vincent-St. Mary HS (OH)",
                country: "USA",
            },
            {
                player: "Kevin Durant",
                team: "BKN",
                number: 7,
                position: "F",
                height: "6-10",
                weight: 240,
                lastAttended: "Texas-Austin",
                country: "USA",
            },
            {
                player: "Giannis Antetokounmpo",
                team: "MIL",
                number: 34,
                position: "F",
                height: "6-11",
                weight: 242,
                lastAttended: "Filathlitikos",
                country: "Greece",
            },
            {
                player: "Stephen Curry",
                team: "GSW",
                number: 30,
                position: "G",
                height: "6-2",
                weight: 185,
                lastAttended: "Davidson",
                country: "USA",
            },
            {
                player: "Lebron James",
                team: "LAL",
                number: 6,
                position: "F",
                height: "6-9",
                weight: 250,
                lastAttended: "St. Vincent-St. Mary HS (OH)",
                country: "USA",
            },
            {
                player: "Kevin Durant",
                team: "BKN",
                number: 7,
                position: "F",
                height: "6-10",
                weight: 240,
                lastAttended: "Texas-Austin",
                country: "USA",
            },
            {
                player: "Giannis Antetokounmpo",
                team: "MIL",
                number: 34,
                position: "F",
                height: "6-11",
                weight: 242,
                lastAttended: "Filathlitikos",
                country: "Greece",
            },
            {
                player: "Stephen Curry",
                team: "GSW",
                number: 30,
                position: "G",
                height: "6-2",
                weight: 185,
                lastAttended: "Davidson",
                country: "USA",
            },
            {
                player: "Lebron James",
                team: "LAL",
                number: 6,
                position: "F",
                height: "6-9",
                weight: 250,
                lastAttended: "St. Vincent-St. Mary HS (OH)",
                country: "USA",
            },
            {
                player: "Kevin Durant",
                team: "BKN",
                number: 7,
                position: "F",
                height: "6-10",
                weight: 240,
                lastAttended: "Texas-Austin",
                country: "USA",
            },
            {
                player: "Giannis Antetokounmpo",
                team: "MIL",
                number: 34,
                position: "F",
                height: "6-11",
                weight: 242,
                lastAttended: "Filathlitikos",
                country: "Greece",
            },
            {
                player: "Stephen Curry",
                team: "GSW",
                number: 30,
                position: "G",
                height: "6-2",
                weight: 185,
                lastAttended: "Davidson",
                country: "USA",
            },
            {
                player: "Lebron James",
                team: "LAL",
                number: 6,
                position: "F",
                height: "6-9",
                weight: 250,
                lastAttended: "St. Vincent-St. Mary HS (OH)",
                country: "USA",
            },
            {
                player: "Kevin Durant",
                team: "BKN",
                number: 7,
                position: "F",
                height: "6-10",
                weight: 240,
                lastAttended: "Texas-Austin",
                country: "USA",
            },
            {
                player: "Giannis Antetokounmpo",
                team: "MIL",
                number: 34,
                position: "F",
                height: "6-11",
                weight: 242,
                lastAttended: "Filathlitikos",
                country: "Greece",
            },
            {
                player: "Stephen Curry",
                team: "GSW",
                number: 30,
                position: "G",
                height: "6-2",
                weight: 185,
                lastAttended: "Davidson",
                country: "USA",
            },
            {
                player: "Lebron James",
                team: "LAL",
                number: 6,
                position: "F",
                height: "6-9",
                weight: 250,
                lastAttended: "St. Vincent-St. Mary HS (OH)",
                country: "USA",
            },
            {
                player: "Kevin Durant",
                team: "BKN",
                number: 7,
                position: "F",
                height: "6-10",
                weight: 240,
                lastAttended: "Texas-Austin",
                country: "USA",
            },
            {
                player: "Giannis Antetokounmpo",
                team: "MIL",
                number: 34,
                position: "F",
                height: "6-11",
                weight: 242,
                lastAttended: "Filathlitikos",
                country: "Greece",
            },
            {
                player: "Stephen Curry",
                team: "GSW",
                number: 30,
                position: "G",
                height: "6-2",
                weight: 185,
                lastAttended: "Davidson",
                country: "USA",
            },
            {
                player: "Lebron James",
                team: "LAL",
                number: 6,
                position: "F",
                height: "6-9",
                weight: 250,
                lastAttended: "St. Vincent-St. Mary HS (OH)",
                country: "USA",
            },
            {
                player: "Kevin Durant",
                team: "BKN",
                number: 7,
                position: "F",
                height: "6-10",
                weight: 240,
                lastAttended: "Texas-Austin",
                country: "USA",
            },
            {
                player: "Giannis Antetokounmpo",
                team: "MIL",
                number: 34,
                position: "F",
                height: "6-11",
                weight: 242,
                lastAttended: "Filathlitikos",
                country: "Greece",
            },
        ];

        const itemsSelected = ref([]);

        return {
            headers,
            items,
            itemsSelected,
        };
    },
});
</script>
<style>
.customize-table {
    border: none;
    position: relative;
    box-sizing: border-box;
}
</style>